version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  build:
    commands:
      - echo Migrate started on `date`
      - make db_migrate
      - echo Migrate completed on `date`


