// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.7.1
// source: blog/app/proto/data/error.proto

package data

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// エラーコード
type ErrorCode int32

const (
	ErrorCode_UNKNOWN           ErrorCode = 0 /// 不明なエラー
	ErrorCode_UNDEFINED_SERVICE ErrorCode = 1 /// サービスがみつからない
	ErrorCode_UNDEFINED_METHOD  ErrorCode = 2 /// メソッドがみつからない
	ErrorCode_NOT_CONNECTED     ErrorCode = 3 /// 通信エラー
	ErrorCode_INVALID_SESSION   ErrorCode = 4 /// セッショントークンエラー
	// データ系
	ErrorCode_DATA_NOT_FOUND     ErrorCode = 200 /// データが見つからない
	ErrorCode_DATA_ALREADY_EXIST ErrorCode = 201 /// データがすでに存在する
	// メンテナンス系
	ErrorCode_UNDER_MAINTENANCE ErrorCode = 300 /// メンテ中
	// アプリエラー系
	ErrorCode_INVALID_ARGUMENT ErrorCode = 401 /// 不正な引数
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:   "UNKNOWN",
		1:   "UNDEFINED_SERVICE",
		2:   "UNDEFINED_METHOD",
		3:   "NOT_CONNECTED",
		4:   "INVALID_SESSION",
		200: "DATA_NOT_FOUND",
		201: "DATA_ALREADY_EXIST",
		300: "UNDER_MAINTENANCE",
		401: "INVALID_ARGUMENT",
	}
	ErrorCode_value = map[string]int32{
		"UNKNOWN":            0,
		"UNDEFINED_SERVICE":  1,
		"UNDEFINED_METHOD":   2,
		"NOT_CONNECTED":      3,
		"INVALID_SESSION":    4,
		"DATA_NOT_FOUND":     200,
		"DATA_ALREADY_EXIST": 201,
		"UNDER_MAINTENANCE":  300,
		"INVALID_ARGUMENT":   401,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_data_error_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_data_error_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_data_error_proto_rawDescGZIP(), []int{0}
}

// エラー
type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode    ErrorCode `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3,enum=proto.data.ErrorCode" json:"error_code,omitempty"` /// エラーコード
	ErrorMessage string    `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                   /// エラーメッセージ
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_data_error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_data_error_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_UNKNOWN
}

func (x *Error) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_data_error_proto protoreflect.FileDescriptor

var file_proto_data_error_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x62, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x34, 0x0a,
	0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0xca, 0x01, 0x0a, 0x09, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44,
	0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x55, 0x4e,
	0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x10, 0x02,
	0x12, 0x11, 0x0a, 0x0d, 0x4e, 0x4f, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x4e, 0x45, 0x43, 0x54, 0x45,
	0x44, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x53,
	0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0e, 0x44, 0x41, 0x54, 0x41,
	0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0xc8, 0x01, 0x12, 0x17, 0x0a,
	0x12, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x41, 0x4c, 0x52, 0x45, 0x41, 0x44, 0x59, 0x5f, 0x45, 0x58,
	0x49, 0x53, 0x54, 0x10, 0xc9, 0x01, 0x12, 0x16, 0x0a, 0x11, 0x55, 0x4e, 0x44, 0x45, 0x52, 0x5f,
	0x4d, 0x41, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x41, 0x4e, 0x43, 0x45, 0x10, 0xac, 0x02, 0x12, 0x15,
	0x0a, 0x10, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41, 0x52, 0x47, 0x55, 0x4d, 0x45,
	0x4e, 0x54, 0x10, 0x91, 0x03, 0x42, 0x0c, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64,
	0x61, 0x74, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_data_error_proto_rawDescOnce sync.Once
	file_proto_data_error_proto_rawDescData = file_proto_data_error_proto_rawDesc
)

func file_proto_data_error_proto_rawDescGZIP() []byte {
	file_proto_data_error_proto_rawDescOnce.Do(func() {
		file_proto_data_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_data_error_proto_rawDescData)
	})
	return file_proto_data_error_proto_rawDescData
}

var file_proto_data_error_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_data_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_data_error_proto_goTypes = []interface{}{
	(ErrorCode)(0), // 0: proto.data.ErrorCode
	(*Error)(nil),  // 1: proto.data.Error
}
var file_proto_data_error_proto_depIdxs = []int32{
	0, // 0: proto.data.Error.error_code:type_name -> proto.data.ErrorCode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_data_error_proto_init() }
func file_proto_data_error_proto_init() {
	if File_proto_data_error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_data_error_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_data_error_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_data_error_proto_goTypes,
		DependencyIndexes: file_proto_data_error_proto_depIdxs,
		EnumInfos:         file_proto_data_error_proto_enumTypes,
		MessageInfos:      file_proto_data_error_proto_msgTypes,
	}.Build()
	File_proto_data_error_proto = out.File
	file_proto_data_error_proto_rawDesc = nil
	file_proto_data_error_proto_goTypes = nil
	file_proto_data_error_proto_depIdxs = nil
}
